version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.9
  INSTALL_NODE_VERSION: 16

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "poetry_similarity_app-development"
    ports:
      - "5000:5000"
      - "2992:2992"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "poetry_similarity_app-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
      ES_HOST: host.docker.internal
      ES_PORT: 9200
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "poetry_similarity_app-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
