[tool.isort]
force_single_line = "True"
line_length = 120
known_first_party = "poetry_similarity_app"
default_section = "THIRDPARTY"
forced_separate = "test_poetry_similarity_app"
skip_glob = ["migrations/*"]
